return {
  { import = "plugins.transparent" },
  { import = "plugins.syntax-highlight" },
  { import = "plugins.treesitter" },
  { import = "plugins.luasnip" },
  { import = "plugins.mason" },
  { import = "plugins.dap" },
  { import = "plugins.copilot" },
  { import = "plugins.code_runner" },
  { import = "plugins.wakatime" },
  { import = "plugins.snacks" },
  { import = "plugins.noice" },
  { import = "plugins.git-conflict" },
  { import = "plugins.avante" },
  { import = "plugins.mcp" },
  { import = "plugins.mini-sessions" },
  { import = "plugins.render-markdown" },
  { import = "plugins.ts-autotag" },
  { import = "plugins.oil" },
  { import = "plugins.lsp-signature" },
  { import = "plugins.namu" },
  { import = "plugins.better-escape" },
  { import = "plugins.kitty-scrollback" },
  { import = "plugins.inlay-hints" },
  { import = "plugins.lsp_lines" },
  -- { import = "nvchad.blink.lazyspec" },
}
